### Create a post
POST localhost:8080/posts
Content-Type: application/json

{
  "postTitle": "Hello world",
  "postContent": "Hello world, in this article..."
}

### Create a post
POST localhost:8080/posts
Content-Type: application/json

{
  "postTitle": "Column is called 'content' in db.",
  "postContent": "Hello world, in this article... 134657"
}

### All posts
GET localhost:8080/posts?page=0

### Search posts
GET localhost:8080/posts?query=hello&page=0

### Search posts
GET localhost:8080/posts?query=4&page=0

###
